name: CI

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  danger:
    uses: ./.github/workflows/danger-run.yml
    with:
      ruby-version: "3.3"
      danger-args: "--dangerfile=Dangerfile.local dry_run --base=${{ github.event.pull_request.base.sha }} --head=${{ github.event.pull_request.head.sha }}"
      report-artifact-name: ci-danger-report
    secrets: inherit
